services:
  - type: web
    name: FES
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: JAVA_OPTS
        value: "-Xmx512m"
